install:
  - curl -Ssf -o rustup-init.exe https://win.rustup.rs/x86_64
  - rustup-init.exe -y
  - rustup component add rustfmt

environment:
  PATH: '%USERPROFILE%\.cargo\bin;%PATH%'

build_script:
  - cmd: cargo fmt --all -- --check
  - cmd: cargo build --release

after_build:
  - 7z a vban_autogain.zip target\release\vban_autogain.exe

artifacts:
  - path: vban_autogain.zip
